const assert=require('assert'),fs=require('fs'),{JSDOM}=require('../node_modules/jsdom'),{performance}=require('perf_hooks');
const html=fs.readFileSync('index.html','utf8'),code=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
const w=new JSDOM(html,{url:'https://fixture.test/',runScripts:'outside-only',pretendToBeVisual:true}).window;
Object.defineProperty(w.navigator,'userAgent',{value:process.env.NTFY_DESKTOP?'Mozilla/5.0 (Macintosh; Intel Mac OS X)':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)'});
const errors=[];w.addEventListener('error',e=>errors.push(e.error));w.console.error=(...args)=>errors.push(args);
w.setInterval=()=>1;w.EventSource=class{constructor(){}close(){}};w.matchMedia=()=>({matches:false,addEventListener(){}});
const boats=Array.from({length:3},(_,i)=>({bid:i,name:'테스트'+i+'호',operator:'테스트선사',region:'충남',port:'오천항',channels:{homepage:'https://example.test/index.php?mid=bk',phone:'010-1234-5678'}}));
let remaining=3;
w.fetch=async(raw,options={})=>{
 const path=String(raw).split('?')[0];let data={};
 if(options.method==='HEAD')return {ok:true,headers:{get:k=>k==='ETag'?'test-v1':''}};
 if(path==='data/boats.json')data={boats};
 if(path==='data/status_homepages.json')data={schema_version:2,updated_at:new Date().toISOString(),by_boat_id:{'2026-10-09':{'1':{boat_id:1,status:'available',remaining,checked_at:new Date().toISOString()}}}};
 if(path==='data/site_health.json')data={sites:{}};
 if(path==='data/ntfy_public.json')data={supports_multi:true,supports_manage:true,supports_min_seats:true,supports_receipts:true,inbox:'fake',server:'https://example.test'};
 if(path.includes('/json?'))return {ok:true,text:async()=>''};
 return {ok:true,json:async()=>JSON.parse(JSON.stringify(data))};
};
w.eval(fs.readFileSync('theme.js','utf8'));w.eval(fs.readFileSync('booking_routes.js','utf8'));w.eval(code+'\n'+fs.readFileSync('bada-ui.js','utf8')+'\nwindow.test={loadData,renderMatrix,selectDate,currentSeason,refreshCalendar,ntfySet,ntfyValues,ntfyBoatOptions,ntfyRestore,ntfyRequest};');
(async()=>{
 await new Promise(r=>setTimeout(r,80));
 assert.equal(errors.length,0,JSON.stringify(errors));
 if(process.env.NTFY_DESKTOP){assert(w.document.querySelector('#ntfySettingsBody').hidden);assert(!w.document.querySelector('#ntfyDeviceNotice').hidden);assert(w.document.querySelector('#ntfyRegister').disabled);await assert.rejects(w.test.ntfyRequest({action:'add'}),/모바일/);}else{assert(!w.document.querySelector('#ntfySettingsBody').hidden);assert(w.document.querySelector('#ntfyDeviceNotice').hidden);}
 const themes=w.document.querySelectorAll('button[data-theme]');
 themes[0].click();assert.equal(w.document.documentElement.dataset.theme,'dark');assert.equal(w.localStorage.getItem('bada-theme'),'dark');
 themes[1].click();assert.equal(w.document.documentElement.dataset.theme,'white');
 themes[2].click();assert.equal(w.document.documentElement.dataset.themeChoice,'system');assert.equal(w.document.documentElement.dataset.theme,'white');
 w.document.querySelector('[data-alert-link]').click();assert(w.document.getElementById('ntfySettings').open);
 w.document.getElementById('tab-rockfish').click();assert(!w.document.getElementById('panel-rockfish').hidden);
 w.document.querySelector('[data-reservation-link]').click();assert(!w.document.getElementById('panel-jjukkumi').hidden);
 const guide=w.document.getElementById('guideDialog');guide.showModal=()=>{guide.open=true};guide.close=()=>{guide.open=false};
 const mobileMenu=w.document.querySelector('.mobile-actions');assert.deepEqual([...mobileMenu.children].map(x=>x.textContent.trim()),['빈자리 알림','선사 안내','']);
 const themeDialog=w.document.getElementById('themeSettingsDialog');themeDialog.showModal=()=>{themeDialog.open=true};themeDialog.close=()=>{themeDialog.open=false};
 w.document.getElementById('themeSettingsOpen').click();assert(themeDialog.open);
 themeDialog.querySelector('[data-theme="dark"]').click();assert.equal(w.document.documentElement.dataset.theme,'dark');assert.equal(w.localStorage.getItem('bada-theme'),'dark');
 themeDialog.querySelector('[data-theme="system"]').click();assert.equal(w.document.documentElement.dataset.themeChoice,'system');
 w.document.getElementById('themeSettingsClose').click();assert(!themeDialog.open);
 w.document.getElementById('operatorGuide').click();assert(guide.open);
 const guideSearch=w.document.getElementById('guideSearch'),visible=()=>[...w.document.querySelectorAll('#guideList .directory-item')].filter(row=>!row.hidden);
 const search=value=>{guideSearch.value=value;guideSearch.dispatchEvent(new w.Event('input',{bubbles:true}))};
 assert.equal(visible().length,3);const firstGuideRow=visible()[0];
 search('테스트1호');assert.equal(visible().length,1);assert(visible()[0].textContent.includes('테스트1호'));assert(visible()[0].querySelector('a'),'booking links preserved');
 search('테스트 선사');assert.equal(visible().length,3);assert.strictEqual(visible()[0],firstGuideRow,'filter preserves DOM');
 search('없는 배');assert.equal(visible().length,0);assert(w.document.getElementById('guideCount').textContent.includes('없습니다'));
 search('');assert.equal(visible().length,3);w.document.getElementById('guideClose').click();assert(!guide.open);
 w.document.getElementById('operatorGuideMobile').click();assert(guide.open);
 const phone=visible()[0].querySelector('a[href^="tel:"]');assert.equal(phone.getAttribute('href'),'tel:01012345678');assert(!phone.hasAttribute('target'),'phone link opens default handler');
 w.document.getElementById('guideClose').click();
 assert(w.document.getElementById('summarySettings').hidden,'public site hides local collector controls');
 w.document.dispatchEvent(new w.CustomEvent('bada:collector',{detail:{running:true,state:'수집 중',step:'실제 테스트 단계',elapsed:'경과 01:00'}}));
 assert(w.document.querySelector('.collection-summary').classList.contains('is-running'));assert(w.document.getElementById('summaryDetail').textContent.includes('실제 테스트 단계'));
 
 const selector='button[data-boat-id="1"][data-date="2026-10-09"]',cell=w.document.querySelector(selector),thead=w.document.querySelector('#matrixTable thead');assert(cell);assert.equal(cell.textContent,'3');
 remaining=4;await w.test.loadData();const t=performance.now();w.test.renderMatrix();const duration=performance.now()-t;
 assert.strictEqual(w.document.querySelector(selector),cell,'keep existing cell DOM on status update');assert.equal(cell.textContent,'4');
 w.test.selectDate('2026-10-09');assert.strictEqual(w.document.querySelector('#matrixTable thead'),thead,'keep header DOM on date selection');assert(cell.parentElement.classList.contains('selected-col'));
 assert.equal(w.document.querySelector('#ntfyPort').options.length,2);assert.equal(w.document.querySelector('#ntfyBoat').options.length,4);
 assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['*']);assert.equal(w.document.querySelector('#ntfyBoatPicker summary').textContent,'배 전체');
 w.test.ntfySet('ntfyBoat',['*','0']);assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['*']);
 w.test.ntfySet('ntfyPort',['*','오천항']);assert.deepEqual(Array.from(w.test.ntfyValues('ntfyPort')),['*']);
 w.test.ntfySet('ntfyBoat',['0']);assert.equal(w.document.querySelector('#ntfyBoatPicker summary').textContent,'테스트0호','real boat ID zero stays individually selectable');
 w.test.ntfyRestore({bid:0,scope_all:false,ports:['*']});assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['0'],'individual zero-ID subscription edit preserves boat');
 w.test.ntfyRestore({bid:0,bids:[],scope_all:true,ports:['*']});assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['*'],'all-boats subscription edit preserves all');
 w.test.ntfySet('ntfyBoat',['1','2']);w.test.ntfyBoatOptions();assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['1','2'],'multiple individual boats preserved');
 w.document.querySelector('#ntfyBoat option[value="*"]').selected=true;w.test.ntfyBoatOptions();assert.deepEqual(Array.from(w.test.ntfyValues('ntfyBoat')),['*'],'restored mixed selection normalized');
 boats[0].name='레전드호';boats[0].port='무창포항';boats[1].name='레전드호';boats[1].port='영흥도';
 await w.test.loadData();w.test.ntfyBoatOptions();
 const labels=[...w.document.querySelector('#ntfyBoat').options].map(o=>o.textContent);
 assert(labels.includes('레전드호 (무창포항)'));assert(labels.includes('레전드호 (영흥도)'));assert(labels.includes('테스트2호'),'unique boat label unchanged');
 w.test.ntfySet('ntfyBoat',['0','1']);assert.equal(w.document.querySelector('#ntfyBoatPicker summary').textContent,'레전드호 (무창포항), 레전드호 (영흥도)');
 w.document.querySelector('#ntfyPort').innerHTML='<option value="*">항구 전체</option><option value="무창포항">무창포항</option>';w.test.ntfySet('ntfyPort',['무창포항']);w.test.ntfyBoatOptions();assert.equal(w.document.querySelector('#ntfyBoat option[value="0"]').textContent,'레전드호 (무창포항)','duplicate port label retained even with single port filter');
 assert(!w.document.querySelector('#ntfyTopics'));assert(!w.document.querySelector('#ntfyDuplicateDialog'));assert.match(w.document.querySelector('#ntfyTopic').value,/^fish-[a-f0-9]{32}$/);
 const dateCheck=w.document.querySelector('[data-alert-date="2026-10-09"]');dateCheck.checked=true;dateCheck.dispatchEvent(new w.Event('change',{bubbles:true}));
 assert.equal(w.document.querySelectorAll('#matrixTable .boat-row').length,1,'date checkbox filters to confirmed seats');
 assert(!w.document.getElementById('availableOperators').hidden);assert(w.document.getElementById('availableOperatorsList').textContent.includes('4석'));
 remaining=0;await w.test.loadData();w.test.renderMatrix();assert.equal(w.document.querySelectorAll('#matrixTable .boat-row').length,0,'fresh zero seats removes row');
 w.document.getElementById('clearAvailabilityDates').click();assert.equal(w.document.querySelectorAll('#matrixTable .boat-row').length,3,'clear restores all rows');
 assert(w.document.getElementById('availableOperators').hidden);
 w.eval("const OriginalDate=Date;Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:['2026-12-01T00:00:00+09:00']))}static now(){return new OriginalDate('2026-12-01T00:00:00+09:00').getTime()}};");
 const season=w.test.currentSeason();assert.equal(season.year,2027);assert.equal(season.start,'2027-09-01');w.test.refreshCalendar();assert.equal(w.document.querySelector('#ntfyDate').max,'2027-11-30');assert.equal(w.document.querySelector('#ntfyDate').value,'2027-09-01');
 w.close();console.log('PASS: complete page initialization, schema 2 display, cells/header preserved on update and date selection, alert selectors; small-fixture update '+Math.round(duration)+'ms');
})().catch(e=>{console.error(e);w.close();process.exitCode=1});
