const assert=require('assert'),fs=require('fs'),{JSDOM}=require('../node_modules/jsdom');
const source=fs.readFileSync('index.html','utf8');
const current=Array.from({length:13},(_,i)=>({bid:i+1,name:'배'+(i+1),port:i<9||i===12?'남항유어선부두':'만석부두',channels:{}}));
const isIncheon=b=>b.canonical_bid==null&&(/^남항/.test(b.port)||/^(?:인천\s*)?만석부두$/.test(b.port));
const old=current.slice(0,12);
let version=1;const requests=[];
const w=new JSDOM('<select id="portFilter"></select><div class="snapshot"><strong></strong></div><div id="matrixWrap"></div>',{runScripts:'outside-only',pretendToBeVisual:true}).window;
w.fetch=async(raw,options={})=>{
 const path=String(raw).split('?')[0];requests.push({raw,options});
 if(options.method==='HEAD')return {ok:true,headers:{get(k){return k==='ETag'?(path==='data/boats.json'?'catalog-'+version:'unchanged'):''}}};
 assert.equal(options.cache,'no-store');assert(String(raw).includes('?v='));
 const data=path==='data/boats.json'?{boats:version===1?old:current}:path==='data/site_health.json'?{sites:{}}:{};
 return {ok:true,json:async()=>JSON.parse(JSON.stringify(data))};
};
const loader=source.slice(source.indexOf('let BOATS=[];'),source.indexOf('function currentSeason('));
const normal=source.slice(source.indexOf('const PORT_ALIASES='),source.indexOf('// Preferred ports first;'));
const init=source.slice(source.indexOf('const smallPorts='),source.indexOf('function initRangePorts('));
const refresh=source.slice(source.indexOf('let dataSignature='),source.indexOf('function startAutoRefresh('));
w.eval('const $=s=>document.querySelector(s);function escapeHtml(v){return String(v)};function renderMatrix(){};function renderCards(){};function renderAlertBar(){};function refreshCatalogSelectors(){};'+loader+normal+init+refresh+';window.test={loadData,initPorts,checkForUpdates,setStamp:async()=>{dataSignature=await dataStamp()}};');
(async()=>{
 await w.test.loadData();w.test.initPorts();
 const select=w.document.querySelector('#portFilter');select.value='인천';
 const text=()=>select.selectedOptions[0].textContent;
 assert.equal(text(),`인천 (${old.filter(isIncheon).length})`);
 await w.test.setStamp();version=2;await w.test.checkForUpdates();
 assert.equal(select.value,'인천','keep selected filter after refreshing');
 assert.equal(text(),`인천 (${current.filter(isIncheon).length})`,'catalog-only update refreshes boat count');
 assert(requests.some(r=>String(r.raw).startsWith('data/boats.json?')&&r.options.method==='HEAD'));
 assert(requests.filter(r=>r.options.method!=='HEAD').every(r=>r.options.cache==='no-store'));
 console.log('PASS: fresh catalog requests, catalog-only update refreshes Incheon count and preserves selection');w.close();
})().catch(e=>{console.error(e);w.close();process.exitCode=1});
