import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './worker.mjs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));
const DB={prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){return {meta:sqlite.prepare(sql).run(...args)}}}},async batch(xs){return Promise.all(xs.map(x=>x.run()))}};
const env={DB,AGENT_TOKEN:'a'.repeat(64)},id='1'.repeat(32),token='2'.repeat(32),origin='https://sangju-hue.github.io';
async function call(path,body,auth,from=origin){return worker.fetch(new Request('https://fixture.workers.dev'+path,{method:body?'POST':'GET',headers:{Origin:from,'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},...(body?{body:JSON.stringify(body)}:{})}),env)}
assert.equal((await worker.fetch(new Request('http://fixture.workers.dev/health'),env)).status,400);
const payload={request_id:id,receipt_token:token,message:'fish1:YWJj'};
assert.equal((await call('/requests',payload)).status,202);
assert.equal((await call('/requests',payload)).status,202);
assert.equal((await call('/requests',{...payload,message:'fish1:ZA=='})).status,409);
assert.equal((await call('/requests',payload,null,'https://bad.test')).status,403);
assert.equal((await call('/agent/requests')).status,403);
assert.equal((await (await call('/agent/requests',null,env.AGENT_TOKEN)).json()).requests.length,1);
assert.equal((await call('/receipts/'+id,null,'3'.repeat(32))).status,404);
assert.equal((await (await call('/receipts/'+id,null,token)).json()).done,false);
await call('/agent/results',{request_id:id,ok:true},env.AGENT_TOKEN);
assert.equal((await (await call('/receipts/'+id,null,token)).json()).ok,true);
assert.equal(sqlite.prepare('SELECT message FROM requests').get().message,null);
await call('/agent/results',{request_id:id,ok:false,error:'changed'},env.AGENT_TOKEN);
assert.equal((await (await call('/receipts/'+id,null,token)).json()).ok,true);
assert.equal((await call('/requests',payload)).status,202);
for(let i=0;i<59;i++)assert.equal((await call('/requests',{...payload,request_id:(100+i).toString(16).padStart(32,'0')})).status,202);
assert.equal((await call('/requests',{...payload,request_id:'f'.repeat(32)})).status,429);
sqlite.prepare('UPDATE requests SET created_at=0').run();
assert.equal((await (await call('/receipts/'+(100).toString(16).padStart(32,'0'),null,token)).json()).ok,false);
await worker.scheduled({},env);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM requests').get().n,0);
console.log('PASS: relay authorization, ownership token, idempotency, privacy, rate limits, expiry and cleanup');
